In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [13]:
print(tf.__version__)

2.11.0


In [4]:
# simplest sequential layer network
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

In [6]:
# compile the model
model.compile(optimizer = 'sgd', loss='mean_squared_error')

In [7]:
# make numpy arras for data
xs = np.array([-1.0,0.0,1.0,2.0,3.0,4.0], dtype=float)
ys = np.array([-3.0,-1.0,1.0,3.0,5.0,7.0])

# as formmula is y=2x-1

In [10]:
# training of neural network
model.fit(xs,ys,epochs = 300)

Epoch 1/300
1/1 [==============================] - 0s 26ms/step - loss: 0.1788
Epoch 2/300
1/1 [==============================] - 0s 29ms/step - loss: 0.1751
Epoch 3/300
1/1 [==============================] - 0s 42ms/step - loss: 0.1715
Epoch 4/300
1/1 [==============================] - 0s 25ms/step - loss: 0.1680
Epoch 5/300
1/1 [==============================] - 0s 21ms/step - loss: 0.1646
Epoch 6/300
1/1 [==============================] - 0s 39ms/step - loss: 0.1612
Epoch 7/300
1/1 [==============================] - 0s 31ms/step - loss: 0.1579
Epoch 8/300
1/1 [==============================] - 0s 27ms/step - loss: 0.1546
Epoch 9/300
1/1 [==============================] - 0s 26ms/step - loss: 0.1514
Epoch 10/300
1/1 [==============================] - 0s 26ms/step - loss: 0.1483
Epoch 11/300
1/1 [==============================] - 0s 32ms/step - loss: 0.1453
Epoch 12/300
1/1 [==============================] - 0s 27ms/step - loss: 0.1423
Epoch 13/300
1/1 [==============================]

In [14]:
# predict now
print(model.predict([11,20,10]))

1/1 [==============================] - 0s 330ms/step
[[20.936548]
 [38.864254]
 [18.94458 ]]


In [20]:
import tensorflow as tf
from tensorflow import keras

# Create a sequential model
model = keras.Sequential()

# Add a Dense layer with 1 neuron and 1 input dimension
model.add(keras.layers.Dense(units=5, input_shape=[1]))

# Compile the model with a mean squared error loss function and an Adam optimizer
model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=0.01))

# Train the model on some input data and labels
model.fit(x=[0, 1, 2, 3, 4], y=[1, 3, 5, 7, 9], epochs=100)


Epoch 1/100
1/1 [==============================] - 4s 4s/step - loss: 28.4763
Epoch 2/100
1/1 [==============================] - 0s 30ms/step - loss: 28.1414
Epoch 3/100
1/1 [==============================] - 0s 30ms/step - loss: 27.8087
Epoch 4/100
1/1 [==============================] - 0s 28ms/step - loss: 27.4783
Epoch 5/100
1/1 [==============================] - 0s 31ms/step - loss: 27.1502
Epoch 6/100
1/1 [==============================] - 0s 31ms/step - loss: 26.8245
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 26.5012
Epoch 8/100
1/1 [==============================] - 0s 35ms/step - loss: 26.1804
Epoch 9/100
1/1 [==============================] - 0s 31ms/step - loss: 25.8620
Epoch 10/100
1/1 [==============================] - 0s 36ms/step - loss: 25.5461
Epoch 11/100
1/1 [==============================] - 0s 35ms/step - loss: 25.2328
Epoch 12/100
1/1 [==============================] - 0s 41ms/step - loss: 24.9220
Epoch 13/100
1/1 [=====================

In [18]:
print(model.predict([11,20,10]))

1/1 [==============================] - 0s 470ms/step
[[19.719255  13.088986  17.236246  10.348908   3.7973146]
 [35.2092    23.092596  30.664412  18.096733   6.162492 ]
 [17.99815   11.977474  15.744228   9.488038   3.5345173]]


In [24]:
fmnist = tf.keras.datasets.fashion_mnist
(train_images , train_labels),(test_images, test_labels) = fmnist.load_data()

4422102/4422102 [==============================] - 9s 2us/step
